#!/usr/bin/bash

# - Generate the song midi
# - Generate the song wav
# - Download images for the search
# - Generate separate album art images
# - combine the albums art images into a video plus music

SEARCH=$1
echo $SEARCH
echo "hits/$SEARCH"

# We need way of specifying the midi location
# python music.py --save hits/new_hit.mid -m -b 120

# echo "Generating WAV"

# fluidsynth --quiet -a pulseaudio -g 5 -m alsa_seq -l \
#   -i /usr/share/soundfonts/FluidR3_GM.sf2 -F hits/new_hit.wav hits/new_hit.mid > /dev/null 2> /dev/null

# $1
# python art.py -s $SEARCH -d | lolcat
# python art.py -s $SEARCH    | lolcat

ffmpeg -r 1 -f image2 -s 1920x1080 -pattern_type glob -i "images/$SEARCH/album_art/*.*.jpg" -vcodec libx264 "hits/$SEARCH.mp4"

ffmpeg -i hits/new_hit.wav -i "hits/$SEARCH.mp4" "hits/${SEARCH}_music_video.mp4"
